[project]
name = "teams-ai-accelerator-python-samples"
version = "0.1.0"
description = "Teams AI Accelerator Python Samples"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
web-browsing-agent = {workspace = true}

[tool.uv.workspace]
members = ["samples/*"]
